#!/usr/bin/env python3
"""Pack a one-file installer for the Grok Bot box.

  python tools/pack-brain.py
"""
from __future__ import annotations

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "brain-install-bundle.py")


def main() -> None:
    router = open(os.path.join(HERE, "brain-router.cjs"), encoding="utf-8").read()
    assign = open(os.path.join(HERE, "brain-assign.py"), encoding="utf-8").read()
    install = open(os.path.join(HERE, "install-brain-router.py"), encoding="utf-8").read()
    install = re.sub(
        r'^EMBED_ROUTER = ""$',
        lambda _: "EMBED_ROUTER = " + repr(router),
        install,
        count=1,
        flags=re.M,
    )
    install = re.sub(
        r'^EMBED_ASSIGN = ""$',
        lambda _: "EMBED_ASSIGN = " + repr(assign),
        install,
        count=1,
        flags=re.M,
    )
    header = (
        "#!/usr/bin/env python3\n"
        "# Generated by pack-brain.py. Copy this file to the Grok Bot box.\n"
        "# Rebuild: python tools/pack-brain.py\n\n"
    )
    # Drop the original shebang from install (header already has one)
    if install.startswith("#!"):
        install = install.split("\n", 1)[1]
    open(OUT, "w", encoding="utf-8", newline="\n").write(header + install)
    compile(open(OUT, encoding="utf-8").read(), OUT, "exec")
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
